<?xml version="1.0"?> 
<robot name="robot_base" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="PI" value="3.1415926"/>
    <xacro:property name="base_link_width" value="0.16" /> 
    <xacro:property name="base_link_length" value="0.25" /> 
    <xacro:property name="base_link_height" value="0.05" /> 
    <xacro:property name="earth_space" value="0.025" />     

    <link name="base_footprint">
      <visual>
        <geometry>
           <box size="0.001 0.001 0.001" />
        </geometry>
      </visual>
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_link_length} ${base_link_width} ${base_link_height}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="blue">
                <color rgba="0 0.5 0.8 1"/>
            </material>
        </visual>
    </link>

     <joint name="base_link2base_footprint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0 0 ${earth_space + base_link_height}" />
    </joint>

    <xacro:property name="wheel_radius" value="0.025" />
    <xacro:property name="wheel_length" value="0.02" />
    <xacro:property name="wheel_offset" value="0.08" /> 

    <xacro:macro name="add_wheels" params="name offset_flag flag">
    <link name="${name}_wheel">
        <visual>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}" />
          </geometry>
          <material name="black" />
        </visual>
    </link>

    <joint name="${name}_wheel2base_link" type="continuous">
        <parent link="base_link" />
        <child link="${name}_wheel" />
        <origin rpy="${PI/2} 0.0 0.0" xyz="${offset_flag * wheel_offset} ${flag * base_link_width/2} ${-(earth_space + base_link_height / 2 - wheel_radius) }" />
        <axis xyz="0 1 0" />
    </joint>
    </xacro:macro>
    <xacro:add_wheels name="left_front" offset_flag="1" flag="1" />
    <xacro:add_wheels name="right_front" offset_flag="1" flag="-1" />
    <xacro:add_wheels name="left_back" offset_flag="-1" flag="1" />
    <xacro:add_wheels name="right_back" offset_flag="-1" flag="-1" />

</robot>
