// Generated by gencpp from file pocker_bot_vrep_description/wheel_vel.msg
// DO NOT EDIT!


#ifndef POCKER_BOT_VREP_DESCRIPTION_MESSAGE_WHEEL_VEL_H
#define POCKER_BOT_VREP_DESCRIPTION_MESSAGE_WHEEL_VEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pocker_bot_vrep_description
{
template <class ContainerAllocator>
struct wheel_vel_
{
  typedef wheel_vel_<ContainerAllocator> Type;

  wheel_vel_()
    : left_vel(0.0)
    , right_vel(0.0)  {
    }
  wheel_vel_(const ContainerAllocator& _alloc)
    : left_vel(0.0)
    , right_vel(0.0)  {
  (void)_alloc;
    }



   typedef float _left_vel_type;
  _left_vel_type left_vel;

   typedef float _right_vel_type;
  _right_vel_type right_vel;





  typedef boost::shared_ptr< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> const> ConstPtr;

}; // struct wheel_vel_

typedef ::pocker_bot_vrep_description::wheel_vel_<std::allocator<void> > wheel_vel;

typedef boost::shared_ptr< ::pocker_bot_vrep_description::wheel_vel > wheel_velPtr;
typedef boost::shared_ptr< ::pocker_bot_vrep_description::wheel_vel const> wheel_velConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator1> & lhs, const ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator2> & rhs)
{
  return lhs.left_vel == rhs.left_vel &&
    lhs.right_vel == rhs.right_vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator1> & lhs, const ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pocker_bot_vrep_description

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74ad8f7ea4d888606e4f41069cec47ff";
  }

  static const char* value(const ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74ad8f7ea4d88860ULL;
  static const uint64_t static_value2 = 0x6e4f41069cec47ffULL;
};

template<class ContainerAllocator>
struct DataType< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pocker_bot_vrep_description/wheel_vel";
  }

  static const char* value(const ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left_vel\n"
"float32 right_vel\n"
;
  }

  static const char* value(const ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_vel);
      stream.next(m.right_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheel_vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pocker_bot_vrep_description::wheel_vel_<ContainerAllocator>& v)
  {
    s << indent << "left_vel: ";
    Printer<float>::stream(s, indent + "  ", v.left_vel);
    s << indent << "right_vel: ";
    Printer<float>::stream(s, indent + "  ", v.right_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POCKER_BOT_VREP_DESCRIPTION_MESSAGE_WHEEL_VEL_H
